# Generated by Django 4.1.1 on 2022-09-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikeshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
