# Generated by Django 4.1.1 on 2022-09-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikeshop', '0002_rename_product_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
