# Generated by Django 4.1.1 on 2022-09-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikeshop', '0003_rename_products_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='test',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.FileField(default='tradesmen.png', upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
